% Ray-tracing data allocation
function [sdata] = Build_sdata(xlength,ylength)
%{
s = struct('r',{[0, 0]},'k',{[0, 0, 0]},...
                'Te',{1},...
                'normal',{[0, 0, 0]},'height',{0},...
                'n',{0},'grad_n',{[0, 0]},...
                'WW_Luminance',{0},'WB_Luminance',{0},'BW_Luminance',{0});
%}
s = struct('r',{[0, 0]},'k',{[0, 0, 0]},...
                'normal',{[0, 0, 0]},'height',{0},...
                'n',{0},'grad_n',{[0, 0]},...
                'ri',{[0,0]}, 'dr',{[0,0]});
sdata = repmat(s,[xlength,ylength]);